<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Generated by doctrine:migrations:diff and kept as generated. See ADR-0007.
 */
final class Version20260830114939 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Hand off the unique and join-column index names to Doctrine, so schema:validate '
            . 'passes and migrations:diff comes back empty.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER INDEX uniq_invitation_token RENAME TO UNIQ_E65FCA445F37A13B');
        $this->addSql('ALTER INDEX uniq_password_reset_token RENAME TO UNIQ_3967A2165F37A13B');
        $this->addSql('ALTER INDEX idx_password_reset_user RENAME TO IDX_3967A216A76ED395');
        $this->addSql('ALTER INDEX uniq_slot_lock_token RENAME TO UNIQ_928442DA189391BE');
        $this->addSql('ALTER INDEX uniq_users_email RENAME TO UNIQ_1483A5E9E7927C74');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER INDEX uniq_e65fca445f37a13b RENAME TO uniq_invitation_token');
        $this->addSql('ALTER INDEX uniq_3967a2165f37a13b RENAME TO uniq_password_reset_token');
        $this->addSql('ALTER INDEX idx_3967a216a76ed395 RENAME TO idx_password_reset_user');
        $this->addSql('ALTER INDEX uniq_928442da189391be RENAME TO uniq_slot_lock_token');
        $this->addSql('ALTER INDEX uniq_1483a5e9e7927c74 RENAME TO uniq_users_email');
    }
}
