[PHP]
memory_limit = 512M
max_execution_time = 60
upload_max_filesize = 2M
post_max_size = 2M
date.timezone = UTC
expose_php = Off
display_errors = Off

[opcache]
opcache.enable = 1
opcache.memory_consumption = 256
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

[Session]
session.auto_start = Off
